export { default as Home } from './Home'
export { default as List } from './List'
export { default as Boot } from './Boot'
export { default as Error } from './Error'
export { default as Games } from './Games'
